FROM node:15.11.0-alpine

ENV PATH ./node_modules/.bin:$PATH

RUN apk add --no-cache --upgrade bash

WORKDIR /apptest

RUN npm install -g npm@7.7.6
RUN npm install -g @vue/cli
RUN npm i -S @vue/cli-service